[tools]
"github:guardian/devenv" = "20260721-123412"
nodejs = "24.21.0" # Must be in sync with .nvmrc

[hooks]
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true