name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - run: corepack prepare pnpm@9.15.2 --activate
      shell: bash

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

      # See https://docs.npmjs.com/trusted-publishers
      # Find the latest version with `npm info npm@latest version`
    - name: Install suitable NPM version for trusted publishing
      run: npm install -g npm@11.6.2
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
