name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

      # See https://docs.npmjs.com/trusted-publishers
      # Find the latest version with `npm info npm@latest version`
    - name: Install suitable NPM version for trusted publishing
      run: npm install -g npm@11.6.2
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
